name: CI

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    lint-test-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Set up environment
              run: cp .env.sample .env

            - name: Start PostgreSQL
              run: docker compose up -d --wait

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn all:test

            - name: Build
              run: yarn all:build

            - name: Stop PostgreSQL
              if: always()
              run: docker compose down -v

    e2e:
        runs-on: ubuntu-latest
        needs: lint-test-build
        strategy:
            fail-fast: false
            matrix:
                app:
                    - name: api
                      e2e: api-e2e
                      port: 3000
                    - name: analytics-api
                      e2e: analytics-api-e2e
                      port: 3002
                    - name: search-api
                      e2e: search-api-e2e
                      port: 3003

        name: e2e (${{ matrix.app.name }})

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Set up environment
              run: cp .env.sample .env

            - name: Start PostgreSQL
              run: docker compose up -d --wait

            - name: Run DB:migrate
              run: yarn db:migrate

            - name: Start ${{ matrix.app.name }}
              run: |
                  yarn nx serve @app/${{ matrix.app.name }} &
                  npx wait-on http://localhost:${{ matrix.app.port }} --timeout 60000

            - name: Run ${{ matrix.app.e2e }} tests
              run: yarn e2e ${{ matrix.app.e2e }} --skip-nx-cache

            - name: Stop PostgreSQL
              if: always()
              run: docker compose down -v
